import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar";
import SupabaseProvider from "@/Providers/supabaseProvider";
import UserProvider from "@/Providers/useProvider";
import ModelProvider from "@/Providers/modelprovider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseProvider>
          <UserProvider>
            <ModelProvider/>
        {/* <Sidebar> */}
        
          {children}
        {/* </Sidebar> */}
      
        </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  );
}
 